spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sms_db?useSSL=false&serverTimezone=UTC
    username: root
    password: EverythingIsConnected
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret: "change-this-very-long-secret-key-at-least-64-bytes-for-hmac"
  expiration-ms: 604800000 # 7 days

logging:
  level:
    org.springframework.security: INFO
